"""Generate Go DICOM dictionary from pydicom's _dicom_dict.py - direct parsing."""
import ast
import os
import subprocess
import sys


def gofmt(path):
    """Align the emitted composite literals the way the checked-in file is.

    Without this the generator's output differs from the file it replaces on 5,182
    whitespace-only lines, because gofmt pads map keys to a common width and
    nothing here does. The data would be identical and the diff unreviewable.
    """
    try:
        subprocess.run(['gofmt', '-w', path], check=True)
    except (OSError, subprocess.CalledProcessError) as exc:
        print(f"warning: gofmt {path} failed ({exc}); output is unformatted", file=sys.stderr)


def parse_dicom_dict(filepath):
    """Parse _dicom_dict.py to extract DicomDictionary and RepeatersDictionary."""
    with open(filepath, 'r', encoding='utf-8') as f:
        source = f.read()

    tree = ast.parse(source)

    dicom_dict = {}
    repeaters_dict = {}

    for node in ast.walk(tree):
        targets = []
        value = None
        if isinstance(node, ast.Assign):
            targets = node.targets
            value = node.value
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target]
            value = node.value

        if value is None or not isinstance(value, ast.Dict):
            continue

        for target in targets:
            if not isinstance(target, ast.Name):
                continue
            if target.id == 'DicomDictionary':
                for k, v in zip(value.keys, value.values):
                    tag = ast.literal_eval(k)
                    if isinstance(v, ast.Tuple):
                        vr = ast.literal_eval(v.elts[0])
                        vm = ast.literal_eval(v.elts[1])
                        name = ast.literal_eval(v.elts[2])
                        retired = ast.literal_eval(v.elts[3])
                        keyword = ast.literal_eval(v.elts[4])
                        dicom_dict[tag] = (vr, vm, name, retired, keyword)
            elif target.id == 'RepeatersDictionary':
                for k, v in zip(value.keys, value.values):
                    mask = ast.literal_eval(k)
                    if isinstance(v, ast.Tuple):
                        vr = ast.literal_eval(v.elts[0])
                        vm = ast.literal_eval(v.elts[1])
                        name = ast.literal_eval(v.elts[2])
                        retired = ast.literal_eval(v.elts[3])
                        keyword = ast.literal_eval(v.elts[4])
                        repeaters_dict[mask] = (vr, vm, name, retired, keyword)

    return dicom_dict, repeaters_dict


def escape_go_string(s):
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    return s


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    dicom_dict_path = os.path.join(script_dir, 'pydicom', 'src', 'pydicom', '_dicom_dict.py')

    dicom_dict, repeaters_dict = parse_dicom_dict(dicom_dict_path)

    lines = []
    lines.append('package godicom')
    lines.append('')
    lines.append('// Code generated by generate_dict.py. DO NOT EDIT.')
    lines.append('')
    # Field widths are what gofmt produces, so regenerating leaves no diff.
    lines.append('// DictEntry holds metadata for a standard DICOM element.')
    lines.append('type DictEntry struct {')
    lines.append('\tVR      string')
    lines.append('\tVM      string')
    lines.append('\tName    string')
    lines.append('\tRetired bool')
    lines.append('\tKeyword string')
    lines.append('}')
    lines.append('')

    # Generate the standard dictionary. Unexported: callers reach it through
    # godicom.Standard(), so the table cannot be mutated from outside the package.
    lines.append('// dicomDictionary maps tags to their standard entries.')
    lines.append('var dicomDictionary = map[Tag]DictEntry{')
    for tag_val in sorted(dicom_dict.keys()):
        entry = dicom_dict[tag_val]
        vr, vm, name, retired, keyword = entry
        retired_bool = 'true' if retired == 'Retired' else 'false'
        tag_hex = f'0x{tag_val:08X}'
        lines.append(f'\tTag({tag_hex}): {{VR: "{vr}", VM: "{vm}", Name: "{escape_go_string(name)}", Retired: {retired_bool}, Keyword: "{escape_go_string(keyword)}"}},')
    lines.append('}')
    lines.append('')

    # Generate keywordToTag map (skip empty keywords). No tag-to-keyword or
    # tag-to-name index is emitted: both were derivable from dicomDictionary by a
    # single map access, so they were 10,000 lines of generated duplicate and two
    # more 5,000-entry maps built at init. This direction is the one that needs an
    # index, because finding a tag by keyword otherwise means scanning.
    lines.append('// keywordToTag maps keywords to tags. The reverse direction needs no')
    lines.append('// index: dicomDictionary[tag].Keyword already answers it.')
    lines.append('var keywordToTag = map[string]Tag{')
    for tag_val in sorted(dicom_dict.keys()):
        entry = dicom_dict[tag_val]
        keyword = entry[4]
        if keyword == '':
            continue
        tag_hex = f'0x{tag_val:08X}'
        lines.append(f'\t"{escape_go_string(keyword)}": Tag({tag_hex}),')
    lines.append('}')
    lines.append('')

    # Generate repeaters dictionary
    lines.append('// repeatersDictionary maps repeating-group mask patterns to entries.')
    lines.append('var repeatersDictionary = map[string]DictEntry{')
    for mask in sorted(repeaters_dict.keys()):
        entry = repeaters_dict[mask]
        vr, vm, name, retired, keyword = entry
        retired_bool = 'true' if retired == 'Retired' else 'false'
        lines.append(f'\t"{mask}": {{VR: "{vr}", VM: "{vm}", Name: "{escape_go_string(name)}", Retired: {retired_bool}, Keyword: "{escape_go_string(keyword)}"}},')
    lines.append('}')

    output = '\n'.join(lines) + '\n'
    # The checked-in file is dictionary_generated.go. This said
    # dicom_dict_generated.go, a name nothing in the tree has, so running the
    # generator produced a second file that redeclared DictEntry and every map in
    # it -- the package stopped compiling rather than the dictionary being updated.
    out_path = os.path.join(script_dir, 'dictionary_generated.go')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(output)

    gofmt(out_path)

    print(f"Generated {out_path} with {len(dicom_dict)} standard entries and {len(repeaters_dict)} repeaters")


if __name__ == '__main__':
    main()
