"""Generate Go UID dictionary from pydicom's _uid_dict.py."""
import ast
import os

NATIVE_ENCODING = {
    "1.2.840.10008.1.2",
    "1.2.840.10008.1.2.1",
    "1.2.840.10008.1.2.2",
    "1.2.840.10008.1.2.1.99",
}

GO_KEYWORDS = {
    "break",
    "case",
    "chan",
    "const",
    "continue",
    "default",
    "defer",
    "else",
    "fallthrough",
    "for",
    "func",
    "go",
    "goto",
    "if",
    "import",
    "interface",
    "map",
    "package",
    "range",
    "return",
    "select",
    "struct",
    "switch",
    "type",
    "var",
}

MANUAL_CONSTS = {
    "NativePixels",
    "PYDICOMImplementationUID",
    "GodicomImplementationUID",
    "JPEGBaseline",
    "JPEGExtended",
    "JPEGLSLossy",
    "VerificationSOPClass",
}


def parse_uid_dict(filepath):
    with open(filepath, encoding="utf-8") as f:
        tree = ast.parse(f.read())

    uid_dict = {}
    for node in ast.walk(tree):
        targets = []
        value = None
        if isinstance(node, ast.Assign):
            targets = node.targets
            value = node.value
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target]
            value = node.value

        if value is None or not isinstance(value, ast.Dict):
            continue

        for target in targets:
            if isinstance(target, ast.Name) and target.id == "UID_dictionary":
                for k, v in zip(value.keys, value.values):
                    uid = ast.literal_eval(k)
                    if isinstance(v, ast.Tuple) and len(v.elts) == 5:
                        name = ast.literal_eval(v.elts[0])
                        uid_type = ast.literal_eval(v.elts[1])
                        info = ast.literal_eval(v.elts[2])
                        retired = ast.literal_eval(v.elts[3])
                        keyword = ast.literal_eval(v.elts[4])
                        uid_dict[uid] = (name, uid_type, info, retired, keyword)

    return uid_dict


def escape_go_string(s):
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    s = s.replace("\n", "\\n")
    s = s.replace("\t", "\\t")
    return s


def is_valid_go_ident(name):
    if not name or name in GO_KEYWORDS:
        return False
    if not (name[0].isalpha() or name[0] == "_"):
        return False
    return all(c.isalnum() or c == "_" for c in name)


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    uid_dict_path = os.path.join(
        script_dir, "pydicom", "src", "pydicom", "_uid_dict.py"
    )
    uid_dict = parse_uid_dict(uid_dict_path)

    dict_lines = []
    dict_lines.append("package uid")
    dict_lines.append("")
    dict_lines.append("// Code generated by generate_uid_dict.py. DO NOT EDIT.")
    dict_lines.append("")
    dict_lines.append("// DictEntry holds metadata for a registered DICOM UID.")
    dict_lines.append("type DictEntry struct {")
    dict_lines.append("\tName      string")
    dict_lines.append("\tType      string")
    dict_lines.append("\tExtraInfo string")
    dict_lines.append("\tRetired   bool")
    dict_lines.append("\tKeyword   string")
    dict_lines.append("}")
    dict_lines.append("")
    dict_lines.append("// Dictionary maps UID values to their metadata.")
    dict_lines.append("var Dictionary = map[string]DictEntry{")
    for uid in sorted(uid_dict.keys()):
        name, uid_type, info, retired, keyword = uid_dict[uid]
        retired_bool = "true" if retired == "Retired" else "false"
        dict_lines.append(
            f'\t"{escape_go_string(uid)}": {{Name: "{escape_go_string(name)}", '
            f'Type: "{escape_go_string(uid_type)}", ExtraInfo: "{escape_go_string(info)}", '
            f'Retired: {retired_bool}, Keyword: "{escape_go_string(keyword)}"}},'
        )
    dict_lines.append("}")
    dict_lines.append("")
    dict_lines.append("// KeywordToUID maps UID keywords to values.")
    dict_lines.append("var KeywordToUID = map[string]UID{")
    for uid in sorted(uid_dict.keys()):
        keyword = uid_dict[uid][4]
        if keyword == "":
            continue
        dict_lines.append(f'\t"{escape_go_string(keyword)}": "{escape_go_string(uid)}",')
    dict_lines.append("}")

    dict_path = os.path.join(script_dir, "uid", "dictionary_generated.go")
    with open(dict_path, "w", encoding="utf-8") as f:
        f.write("\n".join(dict_lines) + "\n")

    const_lines = []
    const_lines.append("package uid")
    const_lines.append("")
    const_lines.append("// Code generated by generate_uid_dict.py. DO NOT EDIT.")
    const_lines.append("")
    const_lines.append("const (")
    seen_keywords = set()
    for uid in sorted(uid_dict.keys()):
        keyword = uid_dict[uid][4]
        if keyword == "" or keyword in seen_keywords or keyword in MANUAL_CONSTS:
            continue
        if not is_valid_go_ident(keyword):
            continue
        seen_keywords.add(keyword)
        const_lines.append(f'\t{keyword} UID = "{escape_go_string(uid)}"')
    const_lines.append(")")

    const_path = os.path.join(script_dir, "uid", "generated.go")
    with open(const_path, "w", encoding="utf-8") as f:
        f.write("\n".join(const_lines) + "\n")

    print(f"Generated {dict_path} with {len(uid_dict)} UIDs")
    print(f"Generated {const_path} with {len(seen_keywords)} constants")


if __name__ == "__main__":
    main()
