"""Generate Go private DICOM dictionary from pydicom's _private_dict.py."""
import ast
import os


def parse_private_dict(filepath):
    with open(filepath, encoding="utf-8") as f:
        tree = ast.parse(f.read())

    private_dict = {}
    for node in ast.walk(tree):
        targets = []
        value = None
        if isinstance(node, ast.Assign):
            targets = node.targets
            value = node.value
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target]
            value = node.value

        if value is None or not isinstance(value, ast.Dict):
            continue

        for target in targets:
            if isinstance(target, ast.Name) and target.id == "private_dictionaries":
                for creator_key, inner in zip(value.keys, value.values):
                    creator = ast.literal_eval(creator_key)
                    if not isinstance(inner, ast.Dict):
                        continue
                    entries = {}
                    for tag_key, tag_val in zip(inner.keys, inner.values):
                        tag_mask = ast.literal_eval(tag_key)
                        if isinstance(tag_val, ast.Tuple) and len(tag_val.elts) == 4:
                            vr = ast.literal_eval(tag_val.elts[0])
                            vm = ast.literal_eval(tag_val.elts[1])
                            name = ast.literal_eval(tag_val.elts[2])
                            retired = ast.literal_eval(tag_val.elts[3])
                            entries[tag_mask] = (vr, vm, name, retired)
                    private_dict[creator] = entries

    return private_dict


def escape_go_string(s):
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    s = s.replace("\n", "\\n")
    s = s.replace("\t", "\\t")
    return s


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    private_dict_path = os.path.join(
        script_dir, "pydicom", "src", "pydicom", "_private_dict.py"
    )
    private_dict = parse_private_dict(private_dict_path)

    lines = []
    lines.append("package godicom")
    lines.append("")
    lines.append("// Code generated by generate_private_dict.py. DO NOT EDIT.")
    lines.append("")
    lines.append("// PrivateDictEntry holds metadata for a private DICOM element.")
    lines.append("type PrivateDictEntry struct {")
    lines.append("\tVR      string")
    lines.append("\tVM      string")
    lines.append("\tName    string")
    lines.append("\tRetired bool")
    lines.append("}")
    lines.append("")
    lines.append("// PrivateDictionaries maps private creator names to tag pattern entries.")
    lines.append("var PrivateDictionaries = map[string]map[string]PrivateDictEntry{")

    entry_count = 0
    for creator in sorted(private_dict.keys()):
        lines.append(f'\t"{escape_go_string(creator)}": {{')
        for tag_mask in sorted(private_dict[creator].keys()):
            vr, vm, name, retired = private_dict[creator][tag_mask]
            retired_bool = "true" if retired == "Retired" else "false"
            lines.append(
                f'\t\t"{escape_go_string(tag_mask)}": '
                f'{{VR: "{escape_go_string(vr)}", VM: "{escape_go_string(vm)}", '
                f'Name: "{escape_go_string(name)}", Retired: {retired_bool}}},'
            )
            entry_count += 1
        lines.append("\t},")

    lines.append("}")

    out_path = os.path.join(script_dir, "private_dictionary_generated.go")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(
        f"Generated {out_path} with {len(private_dict)} creators "
        f"and {entry_count} entries"
    )


if __name__ == "__main__":
    main()
