"""Generate Go DICOM dictionary from pydicom's _dicom_dict.py - direct parsing."""
import ast
import os
import sys


def parse_dicom_dict(filepath):
    """Parse _dicom_dict.py to extract DicomDictionary and RepeatersDictionary."""
    with open(filepath, 'r', encoding='utf-8') as f:
        source = f.read()

    tree = ast.parse(source)

    dicom_dict = {}
    repeaters_dict = {}

    for node in ast.walk(tree):
        targets = []
        value = None
        if isinstance(node, ast.Assign):
            targets = node.targets
            value = node.value
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target]
            value = node.value

        if value is None or not isinstance(value, ast.Dict):
            continue

        for target in targets:
            if not isinstance(target, ast.Name):
                continue
            if target.id == 'DicomDictionary':
                for k, v in zip(value.keys, value.values):
                    tag = ast.literal_eval(k)
                    if isinstance(v, ast.Tuple):
                        vr = ast.literal_eval(v.elts[0])
                        vm = ast.literal_eval(v.elts[1])
                        name = ast.literal_eval(v.elts[2])
                        retired = ast.literal_eval(v.elts[3])
                        keyword = ast.literal_eval(v.elts[4])
                        dicom_dict[tag] = (vr, vm, name, retired, keyword)
            elif target.id == 'RepeatersDictionary':
                for k, v in zip(value.keys, value.values):
                    mask = ast.literal_eval(k)
                    if isinstance(v, ast.Tuple):
                        vr = ast.literal_eval(v.elts[0])
                        vm = ast.literal_eval(v.elts[1])
                        name = ast.literal_eval(v.elts[2])
                        retired = ast.literal_eval(v.elts[3])
                        keyword = ast.literal_eval(v.elts[4])
                        repeaters_dict[mask] = (vr, vm, name, retired, keyword)

    return dicom_dict, repeaters_dict


def escape_go_string(s):
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    return s


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    dicom_dict_path = os.path.join(script_dir, 'pydicom', 'src', 'pydicom', '_dicom_dict.py')

    dicom_dict, repeaters_dict = parse_dicom_dict(dicom_dict_path)

    lines = []
    lines.append('package godicom')
    lines.append('')
    lines.append('// Code generated by generate_dict.py. DO NOT EDIT.')
    lines.append('')
    lines.append('type DictEntry struct {')
    lines.append('\tVR       string')
    lines.append('\tVM       string')
    lines.append('\tName     string')
    lines.append('\tRetired  bool')
    lines.append('\tKeyword  string')
    lines.append('}')
    lines.append('')

    # Generate DicomDictionaryGo
    lines.append('var DicomDictionaryGo = map[Tag]DictEntry{')
    for tag_val in sorted(dicom_dict.keys()):
        entry = dicom_dict[tag_val]
        vr, vm, name, retired, keyword = entry
        retired_bool = 'true' if retired == 'Retired' else 'false'
        tag_hex = f'0x{tag_val:08X}'
        lines.append(f'\tTag({tag_hex}): {{VR: "{vr}", VM: "{vm}", Name: "{escape_go_string(name)}", Retired: {retired_bool}, Keyword: "{escape_go_string(keyword)}"}},')
    lines.append('}')
    lines.append('')

    # Generate keywordToTag map (skip empty keywords)
    lines.append('var keywordToTag = map[string]Tag{')
    for tag_val in sorted(dicom_dict.keys()):
        entry = dicom_dict[tag_val]
        keyword = entry[4]
        if keyword == '':
            continue
        tag_hex = f'0x{tag_val:08X}'
        lines.append(f'\t"{escape_go_string(keyword)}": Tag({tag_hex}),')
    lines.append('}')
    lines.append('')

    # Generate tagToKeyword map (skip empty keywords)
    lines.append('var tagToKeyword = map[Tag]string{')
    for tag_val in sorted(dicom_dict.keys()):
        entry = dicom_dict[tag_val]
        keyword = entry[4]
        if keyword == '':
            continue
        tag_hex = f'0x{tag_val:08X}'
        lines.append(f'\tTag({tag_hex}): "{escape_go_string(keyword)}",')
    lines.append('}')
    lines.append('')

    # Generate tagToName map
    lines.append('var tagToName = map[Tag]string{')
    for tag_val in sorted(dicom_dict.keys()):
        entry = dicom_dict[tag_val]
        name = entry[2]
        tag_hex = f'0x{tag_val:08X}'
        lines.append(f'\tTag({tag_hex}): "{escape_go_string(name)}",')
    lines.append('}')
    lines.append('')

    # Generate repeaters dictionary
    lines.append('// RepeatersDictionaryGo maps mask patterns to entries')
    lines.append('var RepeatersDictionaryGo = map[string]DictEntry{')
    for mask in sorted(repeaters_dict.keys()):
        entry = repeaters_dict[mask]
        vr, vm, name, retired, keyword = entry
        retired_bool = 'true' if retired == 'Retired' else 'false'
        lines.append(f'\t"{mask}": {{VR: "{vr}", VM: "{vm}", Name: "{escape_go_string(name)}", Retired: {retired_bool}, Keyword: "{escape_go_string(keyword)}"}},')
    lines.append('}')

    output = '\n'.join(lines) + '\n'
    out_path = os.path.join(script_dir, 'dicom_dict_generated.go')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(output)

    print(f"Generated {out_path} with {len(dicom_dict)} standard entries and {len(repeaters_dict)} repeaters")


if __name__ == '__main__':
    main()
